CREATE TABLE NRL_mens_match (
  matchId INT NOT NULL,
  tries INT NULL,
  runsDummyHalfMetres INT NULL,
  sinBins INT NULL,
  onReports INT NULL,
  runsHitupMetres INT NULL,
  tryAssists INT NULL,
  penaltyGoalAttempts INT NULL,
  points INT NULL,
  conversionsUnsuccessful INT NULL,
  possessions INT NULL,
  tackleds INT NULL,
  kickMetres INT NULL,
  kicksGeneralPlay INT NULL,
  tackles INT NULL,
  tacklesIneffective INT NULL,
  handlingErrors INT NULL,
  sentOffs INT NULL,
  runsDummyHalf INT NULL,
  squadId INT NOT NULL,
  offloads INT NULL,
  bombKicksCaught INT NULL,
  runsKickReturn INT NULL,
  runsHitup INT NULL,
  fieldGoalAttempts INT NULL,
  conversionAttempts INT NULL,
  penaltiesConceded INT NULL,
  postContactMetres INT NULL,
  position VARCHAR(45) NOT NULL,
  errors INT NULL,
  goalLineDropouts INT NULL,
  fortyTwenty INT NULL,
  conversions INT NULL,
  tryDebits INT NULL,
  missedTackles INT NULL,
  penaltyGoalsUnsuccessful INT NULL,
  kicksCaught INT NULL,
  metresGained INT NULL,
  lineBreaks INT NULL,
  tackleBreaks INT NULL,
  trySaves INT NULL,
  passes INT NULL,
  runMetres INT NULL,
  fieldGoalsUnsuccessful INT NULL,
  lineBreakAssists INT NULL,
  runsNormalMetres INT NULL,
  runsNormal INT NULL,
  runsKickReturnMetres INT NULL,
  playerId INT NOT NULL,
  jumperNumber INT NOT NULL,
  fieldGoals INT NULL,
  penaltyGoals INT NULL,
  runs INT NULL,
  shortDisplayName VARCHAR(45) NOT NULL,
  firstname VARCHAR(45) NOT NULL,
  surname VARCHAR(45) NOT NULL,
  displayName VARCHAR(45) NOT NULL,
  squadName VARCHAR(45) NOT NULL,
  homeId INT NOT NULL,
  awayId INT NOT NULL,
  opponent VARCHAR(45) NOT NULL,
  round INT NOT NULL,
  fixtureId INT NOT NULL,
  sportId INT NOT NULL,
  PRIMARY KEY (matchId)
);
