CREATE TABLE NRL_womens_period (
  tries INT NULL,
  runsDummyHalfMetres INT NULL,
  sinBins INT NULL,
  onReports INT NULL,
  runsHitupMetres INT NULL,
  tryAssists INT NULL,
  ineffectiveTackles INT NULL,
  penaltyGoalAttempts INT NULL,
  points INT NULL,
  conversionsUnsuccessful INT NULL,
  score INT NULL,
  possessions INT NULL,
  tackleds INT NULL,
  kickMetres INT NULL,
  kicksGeneralPlay INT NULL,
  tackles INT NULL,
  incompleteSets INT NULL,
  tacklesIneffective INT NULL,
  period INT NULL,
  handlingErrors INT NULL,
  sentOffs INT NULL,
  runsDummyHalf INT NULL,
  squadId INT NOT NULL,
  offloads INT NULL,
  bombKicksCaught INT NULL,
  runsKickReturn INT NULL,
  runsHitup INT NULL,
  fieldGoalAttempts INT NULL,
  conversionAttempts INT NULL,
  penaltiesConceded INT NULL,
  tacklesMissed INT NULL,
  postContactMetres INT NULL,
  position VARCHAR(45) NOT NULL,
  errors INT NULL,
  goalLineDropouts INT NULL,
  fortyTwenty INT NULL,
  conversions INT NULL,
  missedTackles INT NULL,
  kicksCaught INT NULL,
  metresGained INT NULL,
  lineBreaks INT NULL,
  tackleBreaks INT NULL,
  trySaves INT NULL,
  passes INT NULL,
  runMetres INT NULL,
  lineBreakAssists INT NULL,
  runsNormalMetres INT NULL,
  scrumWins INT NULL,
  runsNormal INT NULL,
  runsKickReturnMetres INT NULL,
  playerId INT NOT NULL,
  jumperNumber INT NOT NULL,
  fieldGoals INT NULL,
  penaltyGoals INT NULL,
  runs INT NULL,
  matchId INT NOT NULL,
  periodId INT NOT NULL,
  PRIMARY KEY (periodId)
);
