CREATE TABLE netball_mens_fixture (
  fixtureId INT NOT NULL,
  periodSecs INT NOT NULL,
  awaySquadName VARCHAR(45) NOT NULL,
  matchType VARCHAR(45) NOT NULL,
  homeSquadId INT NOT NULL,
  homeSquadShortCode VARCHAR(45) NOT NULL,
  homeSquadNickname VARCHAR(45) NOT NULL,
  matchStatus VARCHAR(45) NOT NULL,
  roundNumber INT NOT NULL,
  homeSquadName VARCHAR(45) NOT NULL,
  awaySquadNickname VARCHAR(45) NOT NULL,
  venueId INT NOT NULL,
  awaySquadId INT NOT NULL,
  venueCode VARCHAR(45) NOT NULL,
  localStartTime VARCHAR(45) NOT NULL,
  matchId INT NOT NULL,
  homeSquadScore INT NOT NULL,
  period INT NOT NULL,
  finalCode VARCHAR(45) NULL,
  periodCompleted INT NOT NULL,
  finalShortCode VARCHAR(45) NULL,
  awaySquadScore INT NOT NULL,
  venueName VARCHAR(45) NOT NULL,
  utcStartTime VARCHAR(45) NOT NULL,
  awaySquadCode VARCHAR(45) NOT NULL,
  homeSquadCode VARCHAR(45) NOT NULL,
  awaySquadShortCode VARCHAR(45) NOT NULL,
  matchNumber INT NOT NULL,
  sportId INT NOT NULL,
  PRIMARY KEY (fixtureId)
);
