CREATE TABLE netball_mens_match (
    rebounds INT,
    turnoverHeld INT,
    centrePassToGoalPerc INT,
    penalties INT,
    deflectionWithNoGain INT,
    generalPlayTurnovers INT,
    interceptPassThrown INT,
    gain INT,
    points INT,
    goalMisses INT,
    blocked INT,
    deflectionWithGain INT,
    goalAssists INT,
    tossUpWin INT,
    centrePassReceives INT,
    obstructionPenalties INT,
    feeds INT,
    playerId INT NOT NULL,
    goals INT,
    offsides INT,
    secondPhaseReceive INT,
    badPasses INT,
    breaks INT,
    blocks INT,
    badHands INT,
    missedGoalTurnover INT,
    squadId INT NOT NULL,
    deflectionPossessionGain INT,
    possessionChanges INT,
    startingPositionCode VARCHAR(100),
    goalAttempts INT,
    contactPenalties INT,
    quartersPlayed INT,
    minutesPlayed INT,
    feedWithAttempt INT,
    unforcedTurnovers INT,
    pickups INT,
    currentPositionCode VARCHAR(100),
    gainToGoalPerc INT,
    intercepts INT,
    shortDisplayName VARCHAR(100),
    firstname VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    displayName VARCHAR(100) NOT NULL,
    squadName VARCHAR(100) NOT NULL,
    homeId INT NOT NULL,
    awayId INT NOT NULL,
    opponent VARCHAR(100) NOT NULL,
    round VARCHAR(100) NOT NULL,
    fixtureId INT NOT NULL,
    sportId INT NOT NULL,
    matchId INT NOT NULL,
    PRIMARY KEY (matchId)
);
