CREATE TABLE netball_womens_international_match (
  rebounds INT,
  penalties INT,
  gain INT,
  possessions INT,
  offensiveRebounds INT,
  goalMisses INT,
  blocked INT,
  passes INT,
  goalAssists INT,
  disposals INT,
  tossUpWin INT,
  centrePassReceives INT,
  obstructionPenalties INT,
  feeds INT,
  playerId INT NOT NULL,
  goals INT,
  offsides INT,
  badPasses INT,
  defensiveRebounds INT,
  breaks INT,
  blocks INT,
  badHands INT,
  missedGoalTurnover INT,
  squadId INT NOT NULL,
  startingPositionCode VARCHAR(45) NOT NULL,
  goalAttempts INT,
  deflections INT,
  contactPenalties INT,
  quartersPlayed INT,
  minutesPlayed INT,
  turnovers INT,
  pickups INT,
  currentPositionCode VARCHAR(45) NOT NULL,
  intercepts INT,
  shortDisplayName VARCHAR(45) NOT NULL,
  firstname VARCHAR(45) NOT NULL,
  surname VARCHAR(45) NOT NULL,
  displayName VARCHAR(45) NOT NULL,
  squadName VARCHAR(45) NOT NULL,
  homeId INT NOT NULL,
  awayId INT NOT NULL,
  opponent VARCHAR(45) NOT NULL,
  round INT NOT NULL,
  fixtureId INT NOT NULL,
  sportId INT NOT NULL,
  matchId INT NOT NULL,
  turnoverHeld INT,
  centrePassToGoalPerc INT,
  deflectionWithNoGain INT,
  generalPlayTurnovers INT,
  interceptPassThrown INT,
  points INT,
  deflectionWithGain INT,
  secondPhaseReceive INT,
  deflectionPossessionGain INT,
  possessionChanges INT,
  feedWithAttempt INT,
  unforcedTurnovers INT,
  gainToGoalPerc INT,
  PRIMARY KEY (matchId)
);
