CREATE TABLE netball_womens_international_period (
  rebounds INT,
  turnoverHeld INT,
  centrePassToGoalPerc INT,
  penalties INT,
  deflectionWithNoGain INT,
  generalPlayTurnovers INT,
  interceptPassThrown INT,
  gain INT,
  points INT,
  goalMisses INT,
  blocked INT,
  deflectionWithGain INT,
  goalAssists INT,
  tossUpWin INT,
  centrePassReceives INT,
  obstructionPenalties INT,
  feeds INT,
  playerId INT NOT NULL,
  goals INT,
  offsides INT,
  secondPhaseReceive INT,
  badPasses INT,
  period INT,
  breaks INT,
  blocks INT,
  badHands INT,
  missedGoalTurnover INT,
  squadId INT NOT NULL,
  startingPositionCode VARCHAR(45) NOT NULL,
  possessionChanges INT,
  goalAttempts INT,
  contactPenalties INT,
  quartersPlayed INT,
  minutesPlayed INT,
  feedWithAttempt INT,
  unforcedTurnovers INT,
  pickups INT,
  currentPositionCode VARCHAR(45) NOT NULL,
  gainToGoalPerc INT,
  intercepts INT,
  matchId INT NOT NULL,
  periodId INT NOT NULL,
  PRIMARY KEY (periodId)
);
